plugins:
  - rubocop-rspec

inherit_gem:
  getaround-rubocop:
    - .rubocop.yml
    - .rubocop-rspec.yml

AllCops:
  Exclude:
    - vendor/**/*

Layout/MultilineMethodCallIndentation:
  Description: Vertical alignment results in awkward diffs.
  EnforcedStyle: indented

Layout/MultilineAssignmentLayout:
  Description: Vertical alignment results in awkward diffs.
  EnforcedStyle: same_line

Layout/ElseAlignment:
  Description: Vertical alignment results in awkward diffs.
  Enabled: false

Layout/EndAlignment:
  Description: Vertical alignment results in awkward diffs.
  EnforcedStyleAlignWith: start_of_line
