inherit_gem:
  relaxed-rubocop: .rubocop.yml

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Description: Length is an unreliable metric.
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Description: Similar to prettier's config.
  Enabled: false

Layout/FirstArgumentIndentation:
  Description: Useless indentation is useless.
  Enabled: false

Layout/FirstArrayElementIndentation:
  Description: Useless indentation is useless.
  Enabled: false

Layout/FirstHashElementIndentation:
  Description: Useless indentation is useless.
  Enabled: false

Layout/FirstParameterIndentation:
  Description: Useless indentation is useless.
  Enabled: false
