require:
  - rubocop-rspec

RSpec/NamedSubject:
  Description: No justification to why this is better.
  Enabled: false

RSpec/ExampleLength:
  Description: Exemple length is an unreliable metric.
  Enabled: false

RSpec/MultipleExpectations:
  Description: Exemple count is an unreliable metric.
  Enabled: false

RSpec/MessageSpies:
  Description: Induces unnecessary repetition in the expectation
  Enabled: false
