inherit_gem:
  relaxed-rubocop: .rubocop.yml

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Description: Length is an unreliable metric.
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Description: Similar to prettier's config.
  Enabled: false

Layout/IndentFirstArgument:
  Description: Useless indentation is useless.
  Enabled: false

Layout/IndentFirstArrayElement:
  Description: Useless indentation is useless.
  Enabled: false

Layout/IndentFirstHashElement:
  Description: Useless indentation is useless.
  Enabled: false

Layout/IndentFirstParameter:
  Description: Useless indentation is useless.
  Enabled: false
