require:
  - rubocop-rspec

inherit_from: .rubocop.yml

RSpec/NamedSubject:
  Enabled: false # Increase spec writing complexity

RSpec/ExampleLength:
  Enabled: false # Exemple length is an unreliable metric.

RSpec/MultipleExpectations:
  Enabled: false # Exemple count is an unreliable metric.

RSpec/MessageSpies:
  Enabled: false # Induces unnecessary repetition in the expectation

RSpec/StubbedMock:
  Enabled: false # StubbedMock semantics are different

RSpec/SubjectStub:
  Enabled: false # RSpec/SubjectStub is an accepted pattern

RSpec/VerifiedDoubles:
  Enabled: false # double have a more practical interface