require:
  - rubocop-rspec

inherit_from: .rubocop.yml

RSpec/NamedSubject:
  Enabled: false # Increase spec writing complexity

RSpec/ExampleLength:
  Enabled: false # Exemple length is an unreliable metric.

RSpec/MultipleExpectations:
  Enabled: false # Exemple count is an unreliable metric.

RSpec/MessageSpies:
  Enabled: false # Induces unnecessary repetition in the expectation
